using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace B3cBonsai.Utility.Services.AI
{
    public class GeminiAIService : IAIService
    {
        private readonly HttpClient _httpClient;
        private readonly string _apiKey;
        private readonly string _model;
        private readonly ILogger<GeminiAIService> _logger;

        public GeminiAIService(IConfiguration configuration, ILogger<GeminiAIService> logger)
        {
            _apiKey = configuration["Gemini:ApiKey"];
            _model = configuration["Gemini:Model"] ?? "gemini-1.5-flash";
            _httpClient = new HttpClient();
            _logger = logger;
        }

        public async Task<string> GetChatResponseAsync(string userMessage, string context = "")
        {
            var systemPrompt = "Bạn là chuyên gia tư vấn cây cảnh Bonsai của cửa hàng B3cBonsai. " +
                               "Hãy trả lời khách hàng một cách thân thiện, chuyên nghiệp và hữu ích. " +
                               "Nếu có ngữ cảnh về sản phẩm, hãy sử dụng nó để tư vấn chính xác hoặc gợi ý các sản phẩm liên quan. " +
                               "Hãy trả lời bằng tiếng Việt.";

            var fullPrompt = $"{systemPrompt}\n\nNgữ cảnh: {context}\n\nCâu hỏi khách hàng: {userMessage}";
            return await CallGeminiAsync(fullPrompt);
        }

        public async Task<string> DoubleCheckGrammarAsync(string text)
        {
            var prompt = $"Hãy kiểm tra chính tả và ngữ pháp cho đoạn văn bản sau của nhân viên cửa hàng Bonsai. " +
                         $"Hãy sửa lỗi nếu có và làm cho đoạn văn trôi chảy hơn nhưng vẫn giữ đúng ý nghĩa gốc. " +
                         $"Chỉ trả về đoạn văn bản đã sửa, không giải thích thêm.\n\nVăn bản: {text}";
            return await CallGeminiAsync(prompt);
        }

        public async Task<string> AutoGenerateDescriptionAsync(string productName, string category, string features = "")
        {
            var prompt = $"Hãy viết một mô tả sản phẩm hấp dẫn và tối ưu SEO cho cây cảnh Bonsai có tên '{productName}' " +
                         $"thuộc danh mục '{category}'. " +
                         $"Các đặc điểm nổi bật: {features}. " +
                         $"Hãy bao gồm thông tin về ý nghĩa phong thủy, cách chăm sóc cơ bản và tại sao khách hàng nên sở hữu nó. " +
                         $"Sử dụng định dạng Markdown (hỗ trợ in đậm, danh sách). Trả lời bằng tiếng Việt.";
            return await CallGeminiAsync(prompt);
        }

        public async Task<string> SuggestHotspotsAsync(string productName, string description)
        {
            var prompt = $"Dựa trên tên sản phẩm '{productName}' và mô tả sau: '{description}', " +
                         $"hãy gợi ý 3-5 điểm chú thích (hotspots) thú vị để hiển thị trên mô hình 3D. " +
                         $"Mỗi điểm chú thích nên có một tiêu đề ngắn và một đoạn mô tả ngắn về một bộ phận của cây (vd: bộ rễ, thế cây, lá, hoa). " +
                         $"Trả về định dạng JSON mảng các đối tượng {{ \"title\": \"...\", \"description\": \"...\" }}. " +
                         $"Chỉ trả về JSON, không giải thích gì thêm.";
            return await CallGeminiAsync(prompt);
        }

        private async Task<string> CallGeminiAsync(string prompt)
        {
            if (string.IsNullOrEmpty(_apiKey))
            {
                return "Lỗi: Gemini API Key chưa được cấu hình.";
            }

            try
            {
                var url = $"https://generativelanguage.googleapis.com/v1beta/models/{_model}:generateContent?key={_apiKey}";

                var requestBody = new
                {
                    contents = new[]
                    {
                        new
                        {
                            parts = new[] { new { text = prompt } }
                        }
                    }
                };

                var jsonRequest = JsonSerializer.Serialize(requestBody);
                var content = new StringContent(jsonRequest, Encoding.UTF8, "application/json");

                var response = await _httpClient.PostAsync(url, content);
                response.EnsureSuccessStatusCode();

                var jsonResponse = await response.Content.ReadAsStringAsync();
                using var doc = JsonDocument.Parse(jsonResponse);
                
                var responseText = doc.RootElement
                    .GetProperty("candidates")[0]
                    .GetProperty("content")
                    .GetProperty("parts")[0]
                    .GetProperty("text")
                    .GetString();

                return responseText ?? "Không có phản hồi từ AI.";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Lỗi khi gọi Gemini API");
                return $"Lỗi kết nối AI: {ex.Message}";
            }
        }
    }
}
