namespace B3cBonsai.Utility.Services.AI
{
    public interface IAIService
    {
        Task<string> GetChatResponseAsync(string userMessage, string context = "");
        Task<string> DoubleCheckGrammarAsync(string text);
        Task<string> AutoGenerateDescriptionAsync(string productName, string category, string features = "");
        Task<string> SuggestHotspotsAsync(string productName, string description);
    }
}
